title: "Paguro repo"
remote_theme: pmarsceill/just-the-docs
color_scheme: "light"

show_downloads: false
exclude: 
  - ./javadoc/PaguroElefante/javadoc/legal/

mermaid:
  theme: "default"
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.2.2"