on:
  workflow_call:
jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4 
    - name: Run test and coverage
      working-directory: paguro_web
      run: |
        npm install
        yarn test
        npx jest --coverage