name: Main project workflow

on:
  #push:
  worckflow_call:
    branches:
      - main
      - develop
jobs:

  ktlintCheck:
    name: check format kotlin
    uses: ./.github/workflows/pipeline_ktlint_check.yml

  tsFormatCheck:
    name: check format ts
    uses: ./.github/workflows/pipeline_check_format_ts.yml

  jacoco:
    needs:
      - ktlintCheck
      - tsFormatCheck
    name: test and coverage
    uses: ./.github/workflows/pipeline_jacoco.yml

  release:
    needs: jacoco
    name: Release workflow
    uses: ./.github/workflows/pipeline_release.yml
