name: Codecov workflow

on:
  workflow_call:
jobs:
  codecov:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }} # required
        with:
          fail_ci_if_error: true
          files: ./coverage.yml
          flags: unittests
          token: ${{ secrets.CODECOV_TOKEN }} # required
          verbose: true
