name: Jacoco workflow

on:
  workflow_call:
permissions:
  contents: read
jobs:
  jacoco-java-gradle:
    strategy:
      matrix:
        java-version: [ 11, 16, 17, 18 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Test Coverage
        run: ./gradlew jacocoTestReport

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: ./PaguroElefante/build/**/jacocoTestReport.csv