name: Test and coverage workflow

on:
  workflow_call:
permissions:
  contents: read
  pull-requests: write
jobs:
  jacoco-java-gradle:
    strategy:
      matrix:
        java-version: [ 11, 16, 17, 18 ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run Test Coverage
        run: ./gradlew jacocoTestReport #sonar

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          SONAR_TOKEN: bb07d60656121b5b24e66eacdf25b5ca5e34c503

      - name: Add coverage to PR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |
            ${{ github.workspace }}/**/build/reports/jacoco/**/*.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 40
          min-coverage-changed-files: 60

      - name: Generate JaCoCo Badge
        uses: cicirello/jacoco-badge-generator@v2
        with:
          generate-branches-badge: true
          jacoco-csv-file: ./PaguroElefante/build/**/jacocoTestReport.csv

  #sonarcloud:
   # name: SonarCloud
    #strategy:
     # matrix:
      #  os: [ ubuntu-latest ]
    #runs-on: ${{ matrix.os }}
    #steps:
     # - uses: actions/checkout@v4
      #  with:
       #   fetch-depth: 0
