name: Release workflow

on:
  workflow_call:
permissions:
  contents: write
jobs:
  release:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '>=20.10.0'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npx semantic-release
        id: ver
      - run: |
          echo ${{ steps.ver }}
    outputs:
      newVersion: ${{ steps.ver.outputs.nextVer }}
  updateNodeProjectVersion:
    needs: release
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update
        uses: Klemensas/action-autotag@stable
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.previous_step.outputs.version }}