name: Release workflow

on:
  workflow_call:
jobs:
  release:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v4
        with:
          node-version: '>=20.10.0'
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npx semantic-release
        id: ver
    outputs:
      newVersion: ${{ steps.ver.outputs.nextVer }}