
name: Sonarcloud workflow

on:
  push:
    branches:
     - main
     - develop
  pull_request:
    branches:
     - main
     - develop
jobs:
  #jacoco:
   # name: test and coverage
    #uses: ./.github/workflows/pipeline_jacoco.yml

  sonarcloud:
    #needs: jacoco
    name: SonarCloud
    strategy:
      matrix:

        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Gradle (build and coverage)
        run: |
          chmod +x gradlew
          ./gradlew build
          ./gradlew jacocoTestReport

      - name: npm (build and coverage)
        working-directory: paguro_web
        run: |
          npm install
          npx jest --coverage

      - name: SonarQube Scan
        run:
          chmod +x gradlew
          chmod +x sonar
          ./gradlew build sonar
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
       # with:
        # args: >
         #  -Dsonar.coverage.jacoco.xmlReportPaths=./PaguroElefante/build/reports/jacoco/test/jacocoTestReport.xml
          # -Dsonar.javascript.lcov.reportPaths=./paguro_web/coverage/lcov.info
