
name: Main project workflow

on:
  push:
    branches: [main, branch-*]
jobs:
  #test:
   # name: Test workflow
   # uses: ./.github/workflows/pipeline_test.yml

  jacoco:
      name: Test and coverage
      uses: ./.github/workflows/pipeline_jacoco.yml

  release:
    needs: jacoco
    name: Release workflow
    uses: ./.github/workflows/pipeline_release.yml
