
name: Main project workflow

on:
  push:
    branches: [main]
jobs:
  test:
    name: Jacoco workflow
    uses: ./.github/workflows/pipeline_jacoco.yml

  #codecov:
   # needs: test
   # name: Codecov workflow
   # uses: ./.github/workflows/pipeline_codecov.yml

  release:
    needs: test
    #needs: codecov
    name: Release workflow
    uses: ./.github/workflows/pipeline_release.yml
  #TODO: release
  #- name: Release
   # env:
    #  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #run: |
     # npm install
      #npx semantic-release
    #id: ver
#outputs:
 # newVersion: ${{ steps.ver.outputs.nextVer }}
