on:
  push:
    branches:
      - main
      - develop
jobs:
  build:
    strategy:
        matrix:
          os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4 
    - name: Install modules
      working-directory: paguro_web
      run: npm install
    - name: Run tests
      run: yarn test