
name: Main project workflow

on:
  push:
    branches:
      - main
      - develop
jobs:
  ktlintFormat:
    name: format kotlin
    uses: ./.github/workflows/pipeline_ktlint_format.yml

  ktlintCheck:
    needs: ktlintFormat
    name: check format kotlin
    uses: ./.github/workflows/pipeline_ktlint_check.yml

  jacoco:
    needs: ktlintCheck
    name: test and coverage
    uses: ./.github/workflows/pipeline_jacoco.yml

  release:
    needs: jacoco
    name: Release workflow
    uses: ./.github/workflows/pipeline_release.yml
