name: Codecov workflow

on:
  workflow_call:
jobs:
  codecov:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: 4e37010f-f78d-4e80-80ee-6a558d587c46 # required
        with:
          fail_ci_if_error: true
          token: 4e37010f-f78d-4e80-80ee-6a558d587c46 # required
          verbose: true
