name: Main project workflow

on:
  push:
    branches:
      - main
      - develop
jobs:

  #dovrebbe lanciare solo i test non anche la coverage

  ktlintCheck:
    name: check format kotlin
    uses: ./.github/workflows/pipeline_ktlint_check.yml

  #tsFormatCheck:
   # name: check format ts
   # uses: ./.github/workflows/pipeline_check_format_ts.yml

  jacoco:
    needs:
      - ktlintCheck
    name: test and coverage kotlin
    uses: ./.github/workflows/pipeline_jacoco.yml

  #jest:
   # needs:
    #  - tsFormatCheck
    #name: test and coverage typescript
    #uses: ./.github/workflows/pipeline_test_jest.yml


  release:
    #needs: jacoco
    name: Release workflow
    uses: ./.github/workflows/pipeline_release.yml
