
name: Pull request workflow

on:
  pull_request:
    branches:
      - ele2
      - main
      - develop
jobs:
  #test:
   # name: Test workflow
    #uses: ./.github/workflows/pipeline_test.yml
  test:
    name: Jacoco workflow
    uses: ./.github/workflows/pipeline_jacoco.yml

