name: Release workflow

on:
  workflow_call:
jobs:
  release:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install
          npx semantic-release
        id: ver
  outputs:
   newVersion: ${{ steps.ver.outputs.nextVer }}