
name: Pull request workflow

on:
  pull_request:
    branches: [main, develop]

jobs:
  test:
    strategy:
      matrix:
        java-version: [ 11, 16, 17, 18]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}

      #- name: Setup Gradle
        #uses: gradle/gradle-build-action@v2

      - run: chmod +x ./gradlew
      - run: ./gradlew test
