name: Jacoco workflow

on:
  workflow_call:
jobs:
  test:
    strategy:
      matrix:
        java-version: [ 11, 16, 17, 18]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    permissions:
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java-version }}
      - run: chmod +x ./gradlew
      - run: ./gradlew jacocoTestReport
      - name: Checkout
          uses: actions/checkout@v4
      #- name: Publish Test Results
       # uses: EnricoMi/publish-unit-test-result-action@v2
       # with:
        #  files: |
         #   **/test-results/**/*.xml
          #  **/test-results/**/*.trx
           # **/test-results/**/*.json

      - name: Add coverage to PR
        uses: madrapps/jacoco-report@v1.6.1
        with:
          paths: |  
            ${{ github.workspace }}/**/build/reports/jacoco/**/*.xml,
          token: ${{ secrets.GITHUB_TOKEN }}
