name: Pull request workflow

on:
  workflow_dispatch:
    workflow_run:
      workflows: [ Test workflow, Release project workflow ]
      types: [ completed ]
  pull_request:
    branches:
      - master
      - develop