name: Pull request workflow

on:
  workflow_run:
    workflows: [ Release project workflow ]
    types: [ completed ]
  pull_request:
    branches:
      - master
      - develop
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'LICENSE'
jobs:
  pull-request:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4