name: Ts format check workflow

on:
  workflow_call:
jobs:
  formatCheck:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        run: npm install
      - name: Install and check
        working-directory: paguro_web
        run: |
          npm install 
          npx tsfmt --verify

# tsfmt -r --> corregge i file non formattati e li sostituisce
# tsfmt --verify --> controlla che i file siano formattati
