name: Ts format check workflow

on:
  workflow_call:
jobs:
  formatCheck:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install
        working-directory: paguro_web
        run: npm install #??
      - name: Format
        working-directory: paguro_web
        run: npx tsfmt --verify
