name: Ktlint check workflow

on:
  workflow_call:
jobs:
  ktlintCheck:
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Ti prego
        uses: actions/setup-java@v4
        with:
          java-version: 18
          distribution: 'temurin'
      - name: Format
        run: |
          chmod +x gradlew
          ./gradlew build
          ./gradlew ktlintCheck
